version: '3.9'
services:
  bytebeat-bot:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    mem_limit: 256m
